name: BarterPlus
version: '${project.version}'
main: com.crashcringle.barterplus.BarterPlus
authors: [ Crash_Cringle ]
description: BarterPlus Plugin
api-version: 1.19
depend:
  - Citizens
commands:
  barter:
    description: Trade with a player
    usage: /barter trade <player>
    permission: barterplus.trade
